set(0, 'DefaultLineLineWidth', 2)
set(0,'DefaultFigureColor','white')
set(0, 'DefaultFigurePosition', [420 262 840 525])
set(0, 'DefaultTextFontName', 'Gill Sans MT')
set(0, 'DefaultTextFontSize', 14)
set(0, 'DefaultTextFontWeight', 'normal')
set(0, 'DefaultTextLineStyle', 'none')
set(0, 'DefaultAxesBox', 'off')
set(0, 'DefaultAxesColor','white')
set(0, 'DefaultAxesFontName', 'Gill Sans MT')
set(0, 'DefaultAxesFontSize', 14)
set(0, 'DefaultAxesFontWeight', 'normal')